[phases.setup]
# Install Python dependencies
commands = ["pip install -r requirements.txt"]

[phases.build]
# Prepare the static files
commands = ["python manage.py collectstatic --noinput"]

[phases.start]
# Run the server
commands = ["gunicorn ayur_rich.wsgi:application --bind 0.0.0.0:$PORT"]