[phases.setup]
commands = ["pip install -r requirements.txt"]

[phases.build]
commands = [
    "python manage.py collectstatic --noinput",
    "python manage.py migrate"
]

[phases.start]
commands = ["gunicorn ayur_rich.wsgi:application --bind 0.0.0.0:$PORT"]